### ISSUE TITLE
Swift 4.2 support

### ISSUE THREAD

**Issue by MindaugasJucius** [tunespeak/AlamoRecord#1]
Hi,

Any plans to update this library to support Swift 4.2? This is needed on Xcode 10/iOS 12. 
AlamofireObjectMapper has been updated to support 4.2 version: https://github.com/tristanhimmelman/AlamofireObjectMapper/releases

**Comment by Daltron** [comment]
Hi @MindaugasJucius! 😄 I will definitely do this once I get around to installing xCode 10. However, I don't believe it will be required by xCode10 to have all your code in Swift 4.2. Swift 4 and 4.2 should be completely interchangeable. If you need this as done as soon as possible, it would be great if you could open up a pull request with the changes! 👍

**Comment by MindaugasJucius** [comment]
Hi :) thanks for your fast response. I'll look into what could be done
