### ISSUE TITLE
URL Query?

### ISSUE THREAD

**Issue by Kaakati** [tunespeak/AlamoRecord#3]
Does it support URL Query?

**Comment by Daltron** [comment]
Hi @Kaakati! Do you mean does this library support passing in URL query parameters? If so, the answer is yes! Basically anything that Alamofire supports, so does AlamoRecord! 😄

**Comment by Kaakati** [comment]
Hi @Daltron I didn't know it existed, Is it going to be documented to cover all aspects?

**Comment by Daltron** [comment]
@Kaakati, almost everything has some sort of documentation attached to it within the source code files so please feel free to explore there!

**Comment by Kaakati** [comment]
Definitely, Was looking for an easier way. 👍
